import type { Category, Product, Addition, Variant } from "@/store/chat-store";

export const sampleCategories: Category[] = [
  {
    id: "entradas",
    name: "Entradas",
    icon: "🥗",
    order: 0,
    description: "Para abrir o apetite",
    products: [
      {
        id: "e1",
        name: "Bruschetta Clássica",
        description: "Pão italiano tostado com tomate fresco, manjericão, alho e azeite extra virgem",
        price: 28,
        image: "",
        categoryId: "entradas",
        isActive: true,
        preparationTime: 8,
        additions: [
          { id: "a1", name: "Burrata", price: 15 },
          { id: "a2", name: "Presunto de Parma", price: 12 },
        ],
        variants: [],
        tags: ["Vegetariano"],
        emoji: "🍞",
      },
      {
        id: "e2",
        name: "Carpaccio de Filé Mignon",
        description: "Fatias finas de filé com rúcula, lascas de parmesão e molho mostarda e mel",
        price: 42,
        image: "",
        categoryId: "entradas",
        isActive: true,
        preparationTime: 10,
        additions: [],
        variants: [],
        tags: [],
        emoji: "🥩",
      },
      {
        id: "e3",
        name: "Bolinho de Bacalhau (6 un)",
        description: "Bolinhos artesanais de bacalhau com batata, servidos com molho tártaro",
        price: 38,
        image: "",
        categoryId: "entradas",
        isActive: true,
        preparationTime: 15,
        additions: [],
        variants: [],
        tags: ["Mais Pedido"],
        emoji: "🐟",
      },
      {
        id: "e4",
        name: "Tábua de Frios",
        description: "Seleção de queijos, embutidos, azeitonas e torradas artesanais",
        price: 89,
        image: "",
        categoryId: "entradas",
        isActive: true,
        preparationTime: 12,
        additions: [
          { id: "a3", name: "Azeite Trufado", price: 8 },
        ],
        variants: [
          { id: "v1", name: "2 pessoas", price: 89 },
          { id: "v2", name: "4 pessoas", price: 149 },
        ],
        tags: [],
        emoji: "🧀",
      },
      {
        id: "e5",
        name: "Batata Frita Crocante",
        description: "Batatas fritas crocantes com cheddar, bacon e cebolinha",
        price: 32,
        image: "",
        categoryId: "entradas",
        isActive: true,
        preparationTime: 12,
        additions: [
          { id: "a4", name: "Cheddar Extra", price: 6 },
          { id: "a5", name: "Bacon Extra", price: 8 },
        ],
        variants: [],
        tags: [],
        emoji: "🍟",
      },
    ],
  },
  {
    id: "principais",
    name: "Principais",
    icon: "🍽️",
    order: 1,
    description: "O melhor da casa",
    products: [
      {
        id: "p1",
        name: "Pizza Margherita",
        description: "Molho de tomate San Marzano, mussarela de búfala, manjericão fresco e azeite",
        price: 52,
        image: "",
        categoryId: "principais",
        isActive: true,
        preparationTime: 20,
        additions: [
          { id: "a6", name: "Borda Recheada c/ Catupiry", price: 8 },
          { id: "a7", name: "Extra Mussarela", price: 6 },
          { id: "a8", name: "Trufa Negra", price: 15 },
        ],
        variants: [
          { id: "v3", name: "Pequena (4 fat.)", price: 42 },
          { id: "v4", name: "Média (6 fat.)", price: 52 },
          { id: "v5", name: "Família (8 fat.)", price: 68 },
        ],
        tags: ["Mais Pedido"],
        emoji: "🍕",
      },
      {
        id: "p2",
        name: "Pizza Pepperoni",
        description: "Molho de tomate, mussarela, pepperoni artesanal e orégano",
        price: 58,
        image: "",
        categoryId: "principais",
        isActive: true,
        preparationTime: 20,
        additions: [
          { id: "a9", name: "Borda Recheada", price: 8 },
          { id: "a10", name: "Pimenta Calabresa", price: 5 },
        ],
        variants: [
          { id: "v6", name: "Média (6 fat.)", price: 58 },
          { id: "v7", name: "Família (8 fat.)", price: 72 },
        ],
        tags: [],
        emoji: "🍕",
      },
      {
        id: "p3",
        name: "Filé Mignon ao Molho Madeira",
        description: "Medalhão de filé mignon 220g com molho madeira, acompanhado de purê de batatas e legumes grelhados",
        price: 78,
        image: "",
        categoryId: "principais",
        isActive: true,
        preparationTime: 30,
        additions: [
          { id: "a11", name: "Cogumelos Paris", price: 12 },
          { id: "a12", name: "Bacon Crocante", price: 8 },
          { id: "a13", name: "Queijo Gorgonzola", price: 10 },
        ],
        variants: [
          { id: "v8", name: "220g", price: 78 },
          { id: "v9", name: "320g", price: 98 },
        ],
        tags: ["Premium"],
        emoji: "🥩",
      },
      {
        id: "p4",
        name: "Risoto de Camarão",
        description: "Arroz arbório cremoso com camarões, limão siciliano e coentro",
        price: 68,
        image: "",
        categoryId: "principais",
        isActive: true,
        preparationTime: 25,
        additions: [],
        variants: [],
        tags: [],
        emoji: "🦐",
      },
      {
        id: "p5",
        name: "Salmão Grelhado",
        description: "Filé de salmão com crosta de ervas, arroz de brócolis e molho de maracujá",
        price: 72,
        image: "",
        categoryId: "principais",
        isActive: true,
        preparationTime: 25,
        additions: [
          { id: "a14", name: "Aspargos", price: 10 },
        ],
        variants: [],
        tags: ["Saudável"],
        emoji: "🐟",
      },
      {
        id: "p6",
        name: "Pasta Carbonara",
        description: "Espaguete al dente com bacon, ovos, pecorino romano e pimenta preta",
        price: 48,
        image: "",
        categoryId: "principais",
        isActive: true,
        preparationTime: 18,
        additions: [
          { id: "a15", name: "Parmesão Extra", price: 5 },
        ],
        variants: [],
        tags: [],
        emoji: "🍝",
      },
      {
        id: "p7",
        name: "Smash Burguer Duplo",
        description: "2x blend bovino 90g, queijo cheddar, cebola caramelizada, picles e molho especial no brioche",
        price: 42,
        image: "",
        categoryId: "principais",
        isActive: true,
        preparationTime: 15,
        additions: [
          { id: "a16", name: "Bacon", price: 6 },
          { id: "a17", name: "Ovo Frito", price: 4 },
          { id: "a18", name: "Queijo Extra", price: 5 },
          { id: "a19", name: "Jalapeño", price: 3 },
        ],
        variants: [
          { id: "v10", name: "Simples", price: 32 },
          { id: "v11", name: "Duplo", price: 42 },
          { id: "v12", name: "Triplo", price: 52 },
        ],
        tags: ["Mais Pedido"],
        emoji: "🍔",
      },
      {
        id: "p8",
        name: "Picanha na Brasa",
        description: "Picanha 300g grelhada no ponto, com arroz, farofa, vinagrete e pão de alho",
        price: 89,
        image: "",
        categoryId: "principais",
        isActive: true,
        preparationTime: 28,
        additions: [],
        variants: [
          { id: "v13", name: "300g", price: 89 },
          { id: "v14", name: "450g", price: 129 },
        ],
        tags: ["Premium"],
        emoji: "🥩",
      },
    ],
  },
  {
    id: "bebidas",
    name: "Bebidas",
    icon: "🍺",
    order: 2,
    description: "Para matar a sede",
    products: [
      {
        id: "b1",
        name: "Refrigerante Lata",
        description: "Coca-Cola, Coca Zero, Guaraná Antarctica, Sprite ou Fanta",
        price: 8,
        image: "",
        categoryId: "bebidas",
        isActive: true,
        preparationTime: 1,
        additions: [],
        variants: [
          { id: "v15", name: "Lata 350ml", price: 8 },
          { id: "v16", name: "600ml", price: 12 },
        ],
        tags: [],
        emoji: "🥤",
      },
      {
        id: "b2",
        name: "Água Mineral",
        description: "Água mineral sem gás ou com gás",
        price: 5,
        image: "",
        categoryId: "bebidas",
        isActive: true,
        preparationTime: 1,
        additions: [],
        variants: [],
        tags: [],
        emoji: "💧",
      },
      {
        id: "b3",
        name: "Suco Natural",
        description: "Laranja, limão, maracujá, abacaxi ou abacaxi com hortelã",
        price: 14,
        image: "",
        categoryId: "bebidas",
        isActive: true,
        preparationTime: 5,
        additions: [],
        variants: [
          { id: "v17", name: "300ml", price: 14 },
          { id: "v18", name: "500ml", price: 18 },
        ],
        tags: ["Natural"],
        emoji: "🧃",
      },
      {
        id: "b4",
        name: "IPA Artesanal",
        description: "Cerveja IPA artesanal local, 500ml. Notas cítricas e amargor equilibrado",
        price: 22,
        image: "",
        categoryId: "bebidas",
        isActive: true,
        preparationTime: 1,
        additions: [],
        variants: [],
        tags: ["Artesanal"],
        emoji: "🍺",
      },
      {
        id: "b5",
        name: "Pilsen Premium",
        description: "Brahma, Skol, Antarctica ou Heineken",
        price: 12,
        image: "",
        categoryId: "bebidas",
        isActive: true,
        preparationTime: 1,
        additions: [],
        variants: [
          { id: "v19", name: "Lata 350ml", price: 12 },
          { id: "v20", name: "Long Neck 330ml", price: 14 },
          { id: "v21", name: "Chopp 600ml", price: 18 },
        ],
        tags: ["Mais Pedido"],
        emoji: "🍻",
      },
      {
        id: "b6",
        name: "Caipirinha",
        description: "Limão, açúcar e cachaça artesanal. Também disponível com morango ou maracujá",
        price: 24,
        image: "",
        categoryId: "bebidas",
        isActive: true,
        preparationTime: 5,
        additions: [],
        variants: [
          { id: "v22", name: "Limão", price: 24 },
          { id: "v23", name: "Morango", price: 26 },
          { id: "v24", name: "Maracujá", price: 26 },
        ],
        tags: [],
        emoji: "🍹",
      },
      {
        id: "b7",
        name: "Gin Tônica",
        description: "Gin, água tônica, pepino e zimbro. Clássico refrescante",
        price: 28,
        image: "",
        categoryId: "bebidas",
        isActive: true,
        preparationTime: 4,
        additions: [
          { id: "a20", name: "Frasqueira", price: 12 },
        ],
        variants: [],
        tags: [],
        emoji: "🥂",
      },
      {
        id: "b8",
        name: "Vinho da Casa",
        description: "Tinto ou branco, taça ou garrafa. Seleção do sommelier",
        price: 18,
        image: "",
        categoryId: "bebidas",
        isActive: true,
        preparationTime: 2,
        additions: [],
        variants: [
          { id: "v25", name: "Taça", price: 18 },
          { id: "v26", name: "Garrafa 750ml", price: 89 },
        ],
        tags: [],
        emoji: "🍷",
      },
      {
        id: "b9",
        name: "Chopp Artesanal",
        description: "Puro malte, servido na temperatura ideal",
        price: 18,
        image: "",
        categoryId: "bebidas",
        isActive: true,
        preparationTime: 1,
        additions: [],
        variants: [
          { id: "v27", name: "400ml", price: 18 },
          { id: "v28", name: "600ml", price: 24 },
          { id: "v29", name: "1 Litro", price: 38 },
        ],
        tags: [],
        emoji: "🍺",
      },
    ],
  },
  {
    id: "sobremesas",
    name: "Sobremesas",
    icon: "🍰",
    order: 3,
    description: "Para adoçar o dia",
    products: [
      {
        id: "s1",
        name: "Brownie com Sorvete",
        description: "Brownie de chocolate 70% com sorvete de creme e calda quente",
        price: 28,
        image: "",
        categoryId: "sobremesas",
        isActive: true,
        preparationTime: 10,
        additions: [
          { id: "a21", name: "Calda de Caramelo", price: 4 },
          { id: "a22", name: "Castanha do Pará", price: 5 },
        ],
        variants: [],
        tags: ["Mais Pedido"],
        emoji: "🍫",
      },
      {
        id: "s2",
        name: "Petit Gâteau",
        description: "Bolinho de chocolate com interior cremoso e sorvete de baunilha",
        price: 32,
        image: "",
        categoryId: "sobremesas",
        isActive: true,
        preparationTime: 15,
        additions: [],
        variants: [],
        tags: [],
        emoji: "🧁",
      },
      {
        id: "s3",
        name: "Pudim de Leite",
        description: "Pudim caseiro de leite condensado com calda de caramelo",
        price: 22,
        image: "",
        categoryId: "sobremesas",
        isActive: true,
        preparationTime: 5,
        additions: [],
        variants: [],
        tags: [],
        emoji: "🍮",
      },
      {
        id: "s4",
        name: "Cheesecake de Frutas Vermelhas",
        description: "Cheesecake cremoso com calda de frutas vermelhas frescas",
        price: 26,
        image: "",
        categoryId: "sobremesas",
        isActive: true,
        preparationTime: 8,
        additions: [],
        variants: [],
        tags: [],
        emoji: "🍰",
      },
      {
        id: "s5",
        name: "Açaí na Tigela",
        description: "Açaí cremoso com banana, granola e leite condensado",
        price: 24,
        image: "",
        categoryId: "sobremesas",
        isActive: true,
        preparationTime: 5,
        additions: [
          { id: "a23", name: "Leite em Pó", price: 3 },
          { id: "a24", name: "Morango", price: 5 },
        ],
        variants: [
          { id: "v30", name: "300ml", price: 24 },
          { id: "v31", name: "500ml", price: 32 },
        ],
        tags: [],
        emoji: "🫐",
      },
    ],
  },
  {
    id: "combos",
    name: "Combos",
    icon: "🎯",
    order: 4,
    description: "Melhores combinações",
    products: [
      {
        id: "c1",
        name: "Combo Casal",
        description: "1 Pizza Média + 2 Chopes 400ml + 1 Sobremesa",
        price: 99,
        image: "",
        categoryId: "combos",
        isActive: true,
        preparationTime: 25,
        additions: [],
        variants: [],
        tags: ["Promoção"],
        emoji: "❤️",
      },
      {
        id: "c2",
        name: "Combo Friends",
        description: "Tábua de Frios (4 pessoas) + 4 Chopes 600ml",
        price: 219,
        image: "",
        categoryId: "combos",
        isActive: true,
        preparationTime: 20,
        additions: [],
        variants: [],
        tags: ["Promoção"],
        emoji: "👥",
      },
      {
        id: "c3",
        name: "Executivo Almoço",
        description: "Prato principal + Suco natural + Café",
        price: 45,
        image: "",
        categoryId: "combos",
        isActive: true,
        preparationTime: 15,
        additions: [],
        variants: [],
        tags: ["Seg-Sex", "11h-15h"],
        emoji: "💼",
      },
    ],
  },
];

export const menuStats = {
  totalProducts: sampleCategories.reduce((sum, cat) => sum + cat.products.length, 0),
  totalCategories: sampleCategories.length,
  mostPopular: sampleCategories.flatMap((c) => c.products).filter((p) => p.tags?.includes("Mais Pedido")),
  promotions: sampleCategories.flatMap((c) => c.products).filter((p) => p.tags?.includes("Promoção")),
};